#pragma once

#define BINARY_FILE 0

#define SOCCAR_CORNER_IDS 1
#define SOCCAR_CORNER_VERTICES 2
#define SOCCAR_GOAL_IDS 3
#define SOCCAR_GOAL_VERTICES 4
#define SOCCAR_RAMPS_0_IDS 5
#define SOCCAR_RAMPS_0_VERTICES 6
#define SOCCAR_RAMPS_1_IDS 7
#define SOCCAR_RAMPS_1_VERTICES 8

#define SOCCAR_NAV_GRAPH 9
#define SOCCAR_NAV_NODES 10
#define SOCCAR_NAV_NORMALS 11


#define HOOPS_CORNER_IDS 12
#define HOOPS_CORNER_VERTICES 13
#define HOOPS_NET_IDS 14
#define HOOPS_NET_VERTICES 15
#define HOOPS_RIM_IDS 16
#define HOOPS_RIM_VERTICES 17
#define HOOPS_RAMPS_0_IDS 18
#define HOOPS_RAMPS_0_VERTICES 19
#define HOOPS_RAMPS_1_IDS 20
#define HOOPS_RAMPS_1_VERTICES 21


#define DROPSHOT_IDS 22
#define DROPSHOT_VERTICES 23


#define THROWBACK_GOAL_IDS 24
#define THROWBACK_GOAL_VERTICES 25
#define THROWBACK_CORNER_WALL_0_IDS 26
#define THROWBACK_CORNER_WALL_0_VERTICES 27
#define THROWBACK_CORNER_WALL_1_IDS 28
#define THROWBACK_CORNER_WALL_1_VERTICES 29
#define THROWBACK_CORNER_WALL_2_IDS 30
#define THROWBACK_CORNER_WALL_2_VERTICES 31
#define THROWBACK_BACK_RAMPS_LOWER_IDS 32
#define THROWBACK_BACK_RAMPS_LOWER_VERTICES 33
#define THROWBACK_BACK_RAMPS_UPPER_IDS 34
#define THROWBACK_BACK_RAMPS_UPPER_VERTICES 35
#define THROWBACK_CORNER_RAMPS_LOWER_IDS 36
#define THROWBACK_CORNER_RAMPS_LOWER_VERTICES 37
#define THROWBACK_CORNER_RAMPS_UPPER_IDS 38
#define THROWBACK_CORNER_RAMPS_UPPER_VERTICES 39
#define THROWBACK_SIDE_RAMPS_LOWER_IDS 40
#define THROWBACK_SIDE_RAMPS_LOWER_VERTICES 41
#define THROWBACK_SIDE_RAMPS_UPPER_IDS 42
#define THROWBACK_SIDE_RAMPS_UPPER_VERTICES 43


#define LUT_PATHS 44
#define LUT_TIMES 45
#define LUT_PARAMETERS 46
