#pragma once

#define BINARY_FILE 999

#define SOCCAR_CORNER_IDS 2
#define SOCCAR_CORNER_VERTICES 3
#define SOCCAR_GOAL_IDS 4
#define SOCCAR_GOAL_VERTICES 5
#define SOCCAR_RAMPS_0_IDS 6
#define SOCCAR_RAMPS_0_VERTICES 7
#define SOCCAR_RAMPS_1_IDS 8
#define SOCCAR_RAMPS_1_VERTICES 9

#define SOCCAR_NAV_GRAPH 10
#define SOCCAR_NAV_NODES 11
#define SOCCAR_NAV_NORMALS 12


#define HOOPS_CORNER_IDS 13
#define HOOPS_CORNER_VERTICES 14
#define HOOPS_NET_IDS 15
#define HOOPS_NET_VERTICES 16
#define HOOPS_RIM_IDS 17
#define HOOPS_RIM_VERTICES 18
#define HOOPS_RAMPS_0_IDS 19
#define HOOPS_RAMPS_0_VERTICES 20
#define HOOPS_RAMPS_1_IDS 21
#define HOOPS_RAMPS_1_VERTICES 22


#define DROPSHOT_IDS 23
#define DROPSHOT_VERTICES 24


#define THROWBACK_GOAL_IDS 25
#define THROWBACK_GOAL_VERTICES 26
#define THROWBACK_CORNER_WALL_0_IDS 27
#define THROWBACK_CORNER_WALL_0_VERTICES 28
#define THROWBACK_CORNER_WALL_1_IDS 29
#define THROWBACK_CORNER_WALL_1_VERTICES 30
#define THROWBACK_CORNER_WALL_2_IDS 31
#define THROWBACK_CORNER_WALL_2_VERTICES 32
#define THROWBACK_BACK_RAMPS_LOWER_IDS 33
#define THROWBACK_BACK_RAMPS_LOWER_VERTICES 34
#define THROWBACK_BACK_RAMPS_UPPER_IDS 35
#define THROWBACK_BACK_RAMPS_UPPER_VERTICES 36
#define THROWBACK_CORNER_RAMPS_LOWER_IDS 37
#define THROWBACK_CORNER_RAMPS_LOWER_VERTICES 38
#define THROWBACK_CORNER_RAMPS_UPPER_IDS 39
#define THROWBACK_CORNER_RAMPS_UPPER_VERTICES 40
#define THROWBACK_SIDE_RAMPS_LOWER_IDS 41
#define THROWBACK_SIDE_RAMPS_LOWER_VERTICES 42
#define THROWBACK_SIDE_RAMPS_UPPER_IDS 43
#define THROWBACK_SIDE_RAMPS_UPPER_VERTICES 44

#define REORIENT_ML_MODEL 45
